# Generated by Django 2.0.9 on 2018-12-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(choices=[('CN', 'Control nodes'), ('XCS', 'RBS XCS')], default='CN', max_length=3, verbose_name='type of analysis')),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analyses',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(default='0-0', max_length=21, verbose_name='identifier of edge')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='label of edge')),
            ],
            options={
                'verbose_name': 'edge',
                'verbose_name_plural': 'edges',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled Graph', max_length=255, verbose_name='title of graph')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='description of graph')),
            ],
            options={
                'verbose_name': 'graph',
                'verbose_name_plural': 'graphs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.IntegerField(default=-1, verbose_name='identifier of node')),
                ('label', models.CharField(default='Untitled Node', max_length=255, verbose_name='label of node')),
            ],
            options={
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdgeCN',
            fields=[
                ('edge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graphs.Edge')),
                ('weight', models.CharField(choices=[('N', 'Neutral'), ('+W', 'Positive Weak'), ('+M', 'Positive Medium'), ('+S', 'Positive Strong'), ('-W', 'Negative Weak'), ('-M', 'Negative Medium'), ('-S', 'Negative Strong')], default='N', max_length=2, verbose_name='type of analysis')),
            ],
            options={
                'verbose_name': 'edge',
                'verbose_name_plural': 'edges',
                'abstract': False,
            },
            bases=('graphs.edge',),
        ),
        migrations.CreateModel(
            name='NodeCN',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graphs.Node')),
                ('function', models.CharField(choices=[('L', 'Linear')], default='L', max_length=1, verbose_name='type of analysis')),
                ('controllability', models.CharField(choices=[('N', 'Neutral'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='N', max_length=1, verbose_name='type of analysis')),
                ('importance', models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default='N', max_length=1, verbose_name='type of analysis')),
            ],
            options={
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
                'abstract': False,
            },
            bases=('graphs.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', related_query_name='node', to='graphs.Graph'),
        ),
        migrations.AddField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', related_query_name='edge', to='graphs.Graph'),
        ),
        migrations.AddField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', related_query_name='source', to='graphs.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', related_query_name='target', to='graphs.Node'),
        ),
    ]
