# Generated by Django 2.0.9 on 2019-04-09 00:34

import cctool.common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('CA', 'Controllability'), ('USA', 'Up stream'), ('DSA', 'Down stream'), ('SLA', 'Subjective logic'), ('XCS', 'XCS classifier')], default=cctool.common.enums.AnalysisShortcode('CA'), max_length=3, verbose_name='type of analysis'),
        ),
        migrations.AlterField(
            model_name='edgeplus',
            name='weight',
            field=models.CharField(choices=[('N', 'Neutral'), ('+W', 'Positive Weak'), ('+M', 'Positive Medium'), ('+S', 'Positive Strong'), ('-W', 'Negative Weak'), ('-M', 'Negative Medium'), ('-S', 'Negative Strong')], default=cctool.common.enums.ConnectionShortcode('N'), max_length=2, verbose_name='edge weight'),
        ),
        migrations.AlterField(
            model_name='nodeplus',
            name='controllability',
            field=models.CharField(choices=[('N', 'Neutral'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default=cctool.common.enums.ControllabilityShortcode('N'), max_length=1, verbose_name='node controllability'),
        ),
        migrations.AlterField(
            model_name='nodeplus',
            name='function',
            field=models.CharField(choices=[('L', 'Linear')], default=cctool.common.enums.FunctionShortcode('L'), max_length=1, verbose_name='node function'),
        ),
        migrations.AlterField(
            model_name='nodeplus',
            name='importance',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], default=cctool.common.enums.ImportanceShortcode('N'), max_length=1, verbose_name='node importance'),
        ),
        migrations.AlterField(
            model_name='nodeplus',
            name='vulnerability',
            field=models.CharField(choices=[('N', 'None'), ('E', 'Low'), ('M', 'Medium'), ('H', 'High')], default=cctool.common.enums.VulnerabilityShortcode('N'), max_length=1, verbose_name='node vulnerability'),
        ),
    ]
