# Generated by Django 2.0.9 on 2019-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20190409_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeplus',
            name='vulnerability',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='N', max_length=1, verbose_name='node vulnerability'),
        ),
    ]
