# Generated by Django 2.0.9 on 2019-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_visualization_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeplus',
            name='weight',
            field=models.CharField(choices=[('N', 'Complex'), ('+W', 'Positive Weak'), ('+M', 'Positive Medium'), ('+S', 'Positive Strong'), ('-W', 'Negative Weak'), ('-M', 'Negative Medium'), ('-S', 'Negative Strong')], default='N', max_length=2, verbose_name='edge weight'),
        ),
    ]
