version: '3'

volumes:
  cctool_local_db_data: {}
  cctool_local_db_data_backups: {}
  cctool_local_frontend_vendor: {}
  cctool_local_frontend_index: {}

services:

  # --- Backend ---

  django: &django
    build:
      context: "$CCTOOL"
      dockerfile: ./docker/compose/local/django/Dockerfile
    image: cctool_local_django
    container_name: cctool_local_django
    depends_on:
      - postgres
      - mailhog
      - angularjs
    volumes:
      # Backend
      - ../backend/.coveragerc:/Developer/cctool/backend/.coveragerc
      - ../backend/.dockerignore:/Developer/cctool/backend/.dockerignore
      - ../backend/.editorconfig:/Developer/cctool/backend/.editorconfig
      - ../backend/.gitattributes:/Developer/cctool/backend/.gitattributes
      - ../backend/.pylintrc:/Developer/cctool/backend/.pylintrc
      - ../backend/.travis.yml:/Developer/cctool/backend/.travis.yml
      - ../backend/README.rst:/Developer/cctool/backend/README.rst
      - ../backend/api:/Developer/cctool/backend/api
      - ../backend/celerybeat-schedule:/Developer/cctool/backend/celerybeat-schedule
      - ../backend/config:/Developer/cctool/backend/config
      - ../backend/docs:/Developer/cctool/backend/docs
      - ../backend/locale:/Developer/cctool/backend/locale
      - ../backend/logs:/Developer/cctool/backend/logs
      - ../backend/manage.py:/Developer/cctool/backend/manage.py
      - ../backend/merge_production_dotenvs_in_dotenv.py:/Developer/cctool/backend/merge_production_dotenvs_in_dotenv.py
      - ../backend/pytest.ini:/Developer/cctool/backend/pytest.ini
      - ../backend/requirements:/Developer/cctool/backend/requirements
      - ../backend/setup.cfg:/Developer/cctool/backend/setup.cfg
      - ../backend/cctool/__init__.py:/Developer/cctool/backend/cctool/__init__.py
      - ../backend/cctool/analysers:/Developer/cctool/backend/cctool/analysers
      - ../backend/cctool/common:/Developer/cctool/backend/cctool/common
      - ../backend/cctool/conftest.py:/Developer/cctool/backend/cctool/conftest.py
      - ../backend/cctool/contrib:/Developer/cctool/backend/cctool/contrib
      - ../backend/cctool/dashboard:/Developer/cctool/backend/cctool/dashboard
      - ../backend/cctool/graphs:/Developer/cctool/backend/cctool/graphs
      - ../backend/cctool/taskapp:/Developer/cctool/backend/cctool/taskapp
      - ../backend/cctool/users:/Developer/cctool/backend/cctool/users
      # cctool/static
      - ../backend/cctool/static/css:/Developer/cctool/backend/cctool/static/css
      - ../backend/cctool/static/fancybox:/Developer/cctool/backend/cctool/static/fancybox
      - ../backend/cctool/static/fonts:/Developer/cctool/backend/cctool/static/fonts
      - ../backend/cctool/static/images:/Developer/cctool/backend/cctool/static/images
      - ../backend/cctool/static/js:/Developer/cctool/backend/cctool/static/js
      - ../backend/cctool/static/sass:/Developer/cctool/backend/cctool/static/sass
      - ../frontend/src/app:/Developer/cctool/backend/cctool/static/dashboard/app
      - ../frontend/src/assets:/Developer/cctool/backend/cctool/static/dashboard/assets
      - cctool_local_frontend_vendor:/Developer/cctool/backend/cctool/static/dashboard/vendor
      # cctool/templates
      - ../backend/cctool/templates/403_csrf.html:/Developer/cctool/backend/cctool/templates/403_csrf.html
      - ../backend/cctool/templates/404.html:/Developer/cctool/backend/cctool/templates/404.html
      - ../backend/cctool/templates/500.html:/Developer/cctool/backend/cctool/templates/500.html
      - ../backend/cctool/templates/account:/Developer/cctool/backend/cctool/templates/account
      - ../backend/cctool/templates/base.html:/Developer/cctool/backend/cctool/templates/base.html
      - ../backend/cctool/templates/pages:/Developer/cctool/backend/cctool/templates/pages
      - ../backend/cctool/templates/users:/Developer/cctool/backend/cctool/templates/users
      - cctool_local_frontend_index:/Developer/cctool/backend/cctool/templates/dashboard
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /bin/bash -c "/Developer/cctool/scripts/logo && /Developer/cctool/scripts/start"

  postgres:
    build:
      context: "$CCTOOL"
      dockerfile: ./docker/compose/production/postgres/Dockerfile
    image: cctool_local_postgres
    container_name: cctool_local_postgres
    volumes:
      - cctool_local_db_data:/var/lib/postgresql/data
      - cctool_local_db_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: cctool_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:3.2
    container_name: cctool_local_redis

  celeryworker:
    <<: *django
    image: cctool_local_celeryworker
    container_name: cctool_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    volumes:
      - ./celery:/Developer/cctool/celery
      - ../backend:/Developer/cctool/backend
    ports: []
    command: /bin/bash -c "/Developer/cctool/scripts/logo && /Developer/cctool/scripts/start-celeryworker"

  celerybeat:
    <<: *django
    image: cctool_local_celerybeat
    container_name: cctool_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    volumes:
      - ./celery:/Developer/cctool/celery
      - ../backend:/Developer/cctool/backend
    ports: []
    command: /bin/bash -c "/Developer/cctool/scripts/logo && /Developer/cctool/scripts/start-celerybeat"

  flower:
    <<: *django
    image: cctool_local_flower
    container_name: cctool_local_flower
    ports:
      - "5555:5555"
    command: /bin/bash -c "/Developer/cctool/scripts/logo && /Developer/cctool/scripts/start-flower"

  # --- Frontend ---

  angularjs:
    build:
      context: "$CCTOOL"
      dockerfile: ./docker/compose/local/angularjs/Dockerfile
    image: cctool_local_angularjs
    container_name: cctool_local_angularjs
    volumes:
      - ../frontend/e2e:/Developer/cctool/frontend/e2e
      - ../frontend/gulp:/Developer/cctool/frontend/gulp
      - ../frontend/src:/Developer/cctool/frontend/src
      - ../frontend/.bowerrc:/Developer/cctool/frontend/.bowerrc
      - ../frontend/.editorconfig:/Developer/cctool/frontend/.editorconfig
      - ../frontend/.eslintrc:/Developer/cctool/frontend/.eslintrc
      - ../frontend/.yo-rc.json:/Developer/cctool/frontend/.yo-rc.json
      - ../frontend/bower.json:/Developer/cctool/frontend/bower.json
      - ../frontend/gulpfile.js:/Developer/cctool/frontend/gulpfile.js
      - ../frontend/karma.conf.js:/Developer/cctool/frontend/karma.conf.js
      - ../frontend/package.json:/Developer/cctool/frontend/package.json
      - ../frontend/protractor.conf.js:/Developer/cctool/frontend/protractor.conf.js
      - cctool_local_frontend_vendor:/Developer/cctool/frontend/bower_components
      - cctool_local_frontend_index:/Developer/cctool/frontend/.tmp/serve
    env_file:
      - ./.envs/.local/.angularjs
    command: /bin/bash -c "/Developer/cctool/scripts/logo && /Developer/cctool/scripts/start"
