FROM python:2

MAINTAINER Nicholas Elia <me@nichelia.com>

# Environment variables
ENV REFRESHED_AT 2018-05-27
ENV DEV_DIR="/Developer"
ENV CODE_DIR="${DEV_DIR}/cctool"
ENV BACKEND_CODE_DIR="${CODE_DIR}/backend/"

# Set working directory
RUN mkdir -p $BACKEND_CODE_DIR
WORKDIR $BACKEND_CODE_DIR

# Copy needed files
COPY backend/requirements.txt $BACKEND_CODE_DIR

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                       bash \
                       git \
                       vim \
    && apt-get clean
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash"]