#!/usr/bin/env bash

echo "                                                                            "
echo "                                                                      ...   "
echo "    .cxO00Oxc.     .cxO00kd:.  okkkkkkkkkkkkl                        ,XXX;  "
echo "   oXXXxlcdKXXd  .xXXKdcldXXKc :olloXXX0llll;                        ,XXX;  "
echo "  lXXX;    'kkk, xXXX,    :kkk.     KXXk     ,dO0K0xc     ;xOK0Od;   ,XXX;  "
echo "  OXX0          .XXX0               KXXk   .OXX0c:xXX0. '0XXk:cOXXO. ,XXX;  "
echo "  OXX0          .XXX0               KXXk   oXXX'   OXXx kXXK.  .KXXl ,XXX;  "
echo "  lXXX,    .xxx, kXXX'    ;xxx.     KXXk   oXXX.   OXXx kXXK   .KXXl ,XXX;  "
echo "   dXXKdccoKXXx  .kXXKoccdKXXl      KXXk   .OXXOc:dXXK' '0XXk::kXXO. ,XXX;  "
echo "    .lxO00Oxl.     'lxO00Oxc.       kOOo     ,oO00Ox:     ;dO00Od;   'OOO,  "
echo "                                                                            "
echo "                                                                            "
