#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


echo $'\n\t C C T O O L  L O C A L  C E L E R Y  W O R K E R \n'
sleep 5
echo $'\n\t>> Running celery worker...\n'
mkdir -p "${CELERY_CODE_DIR}/logs"
mkdir -p "${CELERY_CODE_DIR}/celeryworker"
rm -rf "${CELERY_CODE_DIR}/celeryworker/worker*"
celery worker -A cctool.taskapp -Ofair -l DEBUG --pidfile="${CELERY_CODE_DIR}/celeryworker/worker%I.pid" --logfile="${CELERY_CODE_DIR}/logs/%n%I.log"
