name: cctool-dev
root: <%= ENV["CCTOOL"] %>

on_project_start:
  - find ./docker/ -name "*.sh" -exec chmod +x {} \;
  - ./docker/docker_run_development_mode.sh
on_project_stop:
  - ./docker/docker_stop_development_mode.sh

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - htop
        - ./docker/docker_stats.sh
        - cd "$CCTOOL"
  - main-containers:
      layout: even-horizontal
      panes:
        - docker exec -it cctool_local_django bash
        - docker exec -it ccctool_local_angularjs bash
        - docker exec -it cctool_local_postgres bash
  - celery-containers:
      layout: even-horizontal
      panes:
        - docker exec -it cctool_local_celeryworker bash
        - docker exec -it cctool_local_celerybeat bash
        - docker exec -it cctool_local_flower bash
  - other-containers:
      layout: even-horizontal
      panes:
        - docker exec -it cctool_local_mailhog bash
        - docker exec -it cctool_local_redis bash
  - main-logs:
      layout: even-horizontal
      panes:
        - docker logs -f cctool_local_django
        - docker logs -f cctool_local_angularjs
        - docker logs -f cctool_local_postgres
  - celery-logs:
      layout: even-horizontal
      panes:
        - docker logs -f cctool_local_celeryworker
        - docker logs -f cctool_local_celerybeat
        - docker logs -f cctool_local_flower
  - other-logs:
      layout: even-horizontal
      panes:
        - docker logs -f cctool_local_mailhog
        - docker logs -f cctool_local_redis
